name: Huggingface Keep-Alive

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Huggingface Keep-Alive Ping
        run: |
          curl "${{ vars.HF_SPACE_URL }}"
