name: Supabase Keep-Alive

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Supabase Keep-Alive Ping
        run: |
          curl "${{ secrets.SUPABASE_URL }}/rest/v1/keep-alive?select=*" \
            -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
